<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="pythonnet" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="arduino_model.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
	<!-- ビルド時に外部フォルダを自動コピーする設定 -->
	<ItemGroup>
		<!-- mods フォルダの中身を自動で出力先へコピー -->
		<None Include="mods\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		<Compile Remove="python_embed\**" />
		<EmbeddedResource Remove="python_embed\**" />
		<None Remove="python_embed\**" />
		<Page Remove="python_embed\**" />

		<!-- python_embed フォルダの中身を自動で出力先へコピー -->

		<!-- arduino_model.py も自動で出力先へコピー -->
		
		<None Update="ModBuilder.exe">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
	</ItemGroup>

</Project>
