<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <Platforms>AnyCPU;x64</Platforms>
    <ApplicationIcon>app.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <Resource Include="app.ico" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="python_embed\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="pythonnet" Version="3.1.0" />
  </ItemGroup>

  <ItemGroup>
    <None Update="arduino_model.py">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\libcrypto-3.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\libffi-8.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\libssl-3.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\LICENSE.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\pyexpat.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\python.cat">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\python.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\python3.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\python311.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\python311.zip">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\python311._pth">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\pythonw.exe">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\select.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\sqlite3.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\unicodedata.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\vcruntime140.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\vcruntime140_1.dll">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\winsound.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_asyncio.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_bz2.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_ctypes.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_decimal.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_elementtree.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_hashlib.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_lzma.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_msi.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_multiprocessing.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_overlapped.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_queue.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_socket.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_sqlite3.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_ssl.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_uuid.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="python_embed\_zoneinfo.pyd">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>
	<!-- ビルド時に外部フォルダを自動コピーする設定 -->
	<ItemGroup>
		<!-- mods フォルダの中身を自動で出力先へコピー -->
		<None Include="mods\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<!-- python_embed フォルダの中身を自動で出力先へコピー -->
		<None Include="python_embed\**\*">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>

		<!-- arduino_model.py も自動で出力先へコピー -->
		<None Include="arduino_model.py">
			<CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
		</None>
		
		<None Update="ModBuilder.exe">
            <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
        </None>
	</ItemGroup>

</Project>
